#cloud-config
coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    # specify the initial size of your cluster with ?size=X
    discovery: https://discovery.etcd.io/09e3f88c5a47985362fff1f14d52a62c
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    initial-advertise-peer-urls: http://127.0.0.1:2380
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://0.0.0.0:2380,http://0.0.0.0:7001

  update:
    reboot-strategy: off
  units:
    - name: etcd2.service
      command: start
      # TODO: Add drop-ins here, environment file of initial cluster
    - name: fleet.service
      command: start
    - name: application.service
      command: start
      content: |
        [Unit]
        Description= Application
        After=docker.service
        Requires=docker.service
        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker rm %n
        ExecStartPre=/usr/bin/docker pull <#DOCKER_IMAGE#>
        ExecStart=/usr/bin/docker run --rm --name %n <#DOCKER_OPTS#> <#DOCKER_IMAGE#>
        ExecStop=/usr/bin/docker stop %n
        RestartSec=1
        Restart=always
        [Install]
        WantedBy=multi-user.target
